# Generated by Django 3.1.7 on 2021-05-10 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20210510_1701'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactFormMessage',
        ),
    ]
