# Generated by Django 3.1.7 on 2021-05-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_delete_contactformmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
