# Generated by Django 3.1.7 on 2021-06-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20210609_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='firstname',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
